name: build-test-deploy
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - run: echo "$(cat hello_world.txt)"
          - run: npm install
          - run: npm run build
